-- SEC EDGAR Benchmark Queries
-- Generated by generate_queries.py (template-based random generation)
-- 80 queries selected from 392 generated

-- Q1: joins=2, agg=False, sub=False, tables=3, rows=1000, time=5.8ms
SELECT s.name, p.stmt, t.tlabel, p.line, p.plabel
FROM pre p
JOIN sub s ON p.adsh = s.adsh
JOIN tag t ON p.tag = t.tag AND p.version = t.version
WHERE s.form = '8-K' AND p.stmt = 'CI'
      AND t.custom = 0
ORDER BY s.name, p.line
LIMIT 1000;

-- Q2: joins=0, agg=True, sub=True, tables=3, rows=1, time=5.8ms
SELECT DISTINCT n.tag, n.version, COUNT(*) AS cnt
FROM num n
WHERE n.uom = 'shares' AND n.value IS NOT NULL
      AND EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version
                AND p.stmt = 'CI'
      )
GROUP BY n.tag, n.version
ORDER BY cnt DESC
LIMIT 50;

-- Q3: joins=2, agg=True, sub=False, tables=4, rows=50, time=5.8ms
SELECT s.name, p.stmt, n.tag, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'shares' AND p.stmt = 'EQ' AND s.fy = 2023
      AND n.value IS NOT NULL
GROUP BY s.name, p.stmt, n.tag, p.plabel
ORDER BY total_value DESC
LIMIT 50;

-- Q4: joins=1, agg=True, sub=False, tables=3, rows=15, time=5.9ms
SELECT s.fy, s.fp, COUNT(DISTINCT s.cik) AS num_companies,
       SUM(n.value) AS total_value, AVG(n.value) AS avg_value
FROM num n
JOIN sub s ON n.adsh = s.adsh
WHERE n.tag = 'NetIncomeLoss' AND n.uom = 'USD'
      AND n.value IS NOT NULL AND s.fp IN ('Q1', 'Q2', 'Q3', 'Q4', 'FY')
GROUP BY s.fy, s.fp
ORDER BY s.fy, s.fp;

-- Q5: joins=1, agg=True, sub=False, tables=2, rows=5, time=5.9ms
SELECT n.tag, t.tlabel, t.datatype,
       COUNT(DISTINCT n.adsh) AS num_filings,
       COUNT(*) AS total_entries,
       SUM(CASE WHEN n.value > 0 THEN 1 ELSE 0 END) AS positive_count,
       SUM(CASE WHEN n.value < 0 THEN 1 ELSE 0 END) AS negative_count
FROM num n
JOIN tag t ON n.tag = t.tag AND n.version = t.version
WHERE n.ddate BETWEEN 20220101 AND 20241231 AND n.value IS NOT NULL
      AND t.custom = 0
GROUP BY n.tag, t.tlabel, t.datatype
HAVING COUNT(DISTINCT n.adsh) > 100
ORDER BY num_filings DESC
LIMIT 100;

-- Q6: joins=1, agg=True, sub=False, tables=2, rows=1, time=6.0ms
SELECT t.tlabel, t.datatype, COUNT(*) AS usage_count,
       COUNT(DISTINCT p.adsh) AS filing_count
FROM pre p
JOIN tag t ON p.tag = t.tag AND p.version = t.version
WHERE p.stmt = 'BS' AND t.tlabel IS NOT NULL
GROUP BY t.tlabel, t.datatype
HAVING COUNT(*) > 5
ORDER BY usage_count DESC
LIMIT 100;

-- Q7: joins=1, agg=True, sub=False, tables=2, rows=5, time=6.0ms
SELECT n.tag, t.tlabel, t.datatype,
       COUNT(DISTINCT n.adsh) AS num_filings,
       COUNT(*) AS total_entries,
       SUM(CASE WHEN n.value > 0 THEN 1 ELSE 0 END) AS positive_count,
       SUM(CASE WHEN n.value < 0 THEN 1 ELSE 0 END) AS negative_count
FROM num n
JOIN tag t ON n.tag = t.tag AND n.version = t.version
WHERE n.ddate BETWEEN 20220101 AND 20241231 AND n.value IS NOT NULL
      AND t.custom = 0
GROUP BY n.tag, t.tlabel, t.datatype
HAVING COUNT(DISTINCT n.adsh) > 100
ORDER BY num_filings DESC
LIMIT 200;

-- Q8: joins=1, agg=True, sub=False, tables=3, rows=12, time=6.1ms
SELECT s.form, s.fy, COUNT(*) AS num_lines,
       COUNT(DISTINCT p.tag) AS distinct_tags,
       AVG(p.line) AS avg_line
FROM pre p
JOIN sub s ON p.adsh = s.adsh
WHERE p.stmt = 'EQ'
GROUP BY s.form, s.fy
ORDER BY num_lines DESC
LIMIT 200;

-- Q9: joins=0, agg=True, sub=True, tables=3, rows=1, time=6.1ms
SELECT DISTINCT n.tag, n.version, COUNT(*) AS cnt
FROM num n
WHERE n.uom = 'pure' AND n.value IS NOT NULL
      AND EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version
                AND p.stmt = 'CF'
      )
GROUP BY n.tag, n.version
ORDER BY cnt DESC
LIMIT 200;

-- Q10: joins=1, agg=True, sub=False, tables=2, rows=5, time=6.1ms
SELECT n.tag, t.tlabel, t.datatype,
       COUNT(DISTINCT n.adsh) AS num_filings,
       COUNT(*) AS total_entries,
       SUM(CASE WHEN n.value > 0 THEN 1 ELSE 0 END) AS positive_count,
       SUM(CASE WHEN n.value < 0 THEN 1 ELSE 0 END) AS negative_count
FROM num n
JOIN tag t ON n.tag = t.tag AND n.version = t.version
WHERE n.ddate BETWEEN 20220101 AND 20221231 AND n.value IS NOT NULL
      AND t.custom = 0
GROUP BY n.tag, t.tlabel, t.datatype
HAVING COUNT(DISTINCT n.adsh) > 100
ORDER BY num_filings DESC
LIMIT 100;

-- Q11: joins=1, agg=True, sub=True, tables=3, rows=416, time=6.1ms
SELECT s.name, n.tag, n.value
FROM num n
JOIN sub s ON n.adsh = s.adsh
WHERE n.uom = 'pure' AND s.fy = 2024 AND n.value IS NOT NULL
      AND n.value = (
          SELECT MAX(n2.value)
          FROM num n2
          WHERE n2.tag = n.tag AND n2.adsh = n.adsh AND n2.uom = 'pure'
      )
ORDER BY n.value DESC
LIMIT 1000;

-- Q12: joins=1, agg=True, sub=False, tables=2, rows=1, time=6.1ms
SELECT t.tlabel, t.datatype, COUNT(*) AS usage_count,
       COUNT(DISTINCT p.adsh) AS filing_count
FROM pre p
JOIN tag t ON p.tag = t.tag AND p.version = t.version
WHERE p.stmt = 'EQ' AND t.tlabel IS NOT NULL
GROUP BY t.tlabel, t.datatype
HAVING COUNT(*) > 5
ORDER BY usage_count DESC
LIMIT 1000;

-- Q13: joins=2, agg=True, sub=False, tables=4, rows=50, time=6.1ms
SELECT s.name, p.stmt, n.tag, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'shares' AND p.stmt = 'CF' AND s.fy = 2024
      AND n.value IS NOT NULL
GROUP BY s.name, p.stmt, n.tag, p.plabel
ORDER BY total_value DESC
LIMIT 50;

-- Q14: joins=1, agg=True, sub=False, tables=2, rows=5, time=6.1ms
SELECT n.tag, t.tlabel, t.datatype,
       COUNT(DISTINCT n.adsh) AS num_filings,
       COUNT(*) AS total_entries,
       SUM(CASE WHEN n.value > 0 THEN 1 ELSE 0 END) AS positive_count,
       SUM(CASE WHEN n.value < 0 THEN 1 ELSE 0 END) AS negative_count
FROM num n
JOIN tag t ON n.tag = t.tag AND n.version = t.version
WHERE n.ddate BETWEEN 20240101 AND 20241231 AND n.value IS NOT NULL
      AND t.custom = 0
GROUP BY n.tag, t.tlabel, t.datatype
HAVING COUNT(DISTINCT n.adsh) > 100
ORDER BY num_filings DESC
LIMIT 500;

-- Q15: joins=1, agg=True, sub=False, tables=2, rows=5, time=6.2ms
SELECT s.sic, COUNT(DISTINCT s.cik) AS num_companies,
       COUNT(*) AS num_values,
       SUM(n.value) AS total_value,
       AVG(n.value) AS avg_value,
       MIN(n.value) AS min_value,
       MAX(n.value) AS max_value
FROM num n
JOIN sub s ON n.adsh = s.adsh
WHERE n.uom = 'USD' AND s.fy = 2022
      AND s.sic IS NOT NULL AND n.value IS NOT NULL AND n.value > 0
GROUP BY s.sic
HAVING COUNT(DISTINCT s.cik) >= 3
ORDER BY total_value DESC
LIMIT 50;

-- Q16: joins=1, agg=True, sub=False, tables=3, rows=12, time=6.2ms
SELECT s.form, s.fy, COUNT(*) AS num_lines,
       COUNT(DISTINCT p.tag) AS distinct_tags,
       AVG(p.line) AS avg_line
FROM pre p
JOIN sub s ON p.adsh = s.adsh
WHERE p.stmt = 'BS'
GROUP BY s.form, s.fy
ORDER BY num_lines DESC
LIMIT 100;

-- Q17: joins=1, agg=True, sub=False, tables=3, rows=12, time=6.2ms
SELECT s.form, s.fy, COUNT(*) AS num_lines,
       COUNT(DISTINCT p.tag) AS distinct_tags,
       AVG(p.line) AS avg_line
FROM pre p
JOIN sub s ON p.adsh = s.adsh
WHERE p.stmt = 'CI'
GROUP BY s.form, s.fy
ORDER BY num_lines DESC
LIMIT 200;

-- Q18: joins=0, agg=True, sub=True, tables=3, rows=1, time=6.2ms
SELECT DISTINCT n.tag, n.version, COUNT(*) AS cnt
FROM num n
WHERE n.uom = 'pure' AND n.value IS NOT NULL
      AND EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version
                AND p.stmt = 'IS'
      )
GROUP BY n.tag, n.version
ORDER BY cnt DESC
LIMIT 500;

-- Q19: joins=1, agg=True, sub=False, tables=2, rows=1, time=6.3ms
SELECT t.tlabel, t.datatype, COUNT(*) AS usage_count,
       COUNT(DISTINCT p.adsh) AS filing_count
FROM pre p
JOIN tag t ON p.tag = t.tag AND p.version = t.version
WHERE p.stmt = 'EQ' AND t.tlabel IS NOT NULL
GROUP BY t.tlabel, t.datatype
HAVING COUNT(*) > 5
ORDER BY usage_count DESC
LIMIT 500;

-- Q20: joins=0, agg=True, sub=True, tables=3, rows=1, time=6.4ms
SELECT DISTINCT n.tag, n.version, COUNT(*) AS cnt
FROM num n
WHERE n.uom = 'shares' AND n.value IS NOT NULL
      AND EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version
                AND p.stmt = 'CF'
      )
GROUP BY n.tag, n.version
ORDER BY cnt DESC
LIMIT 200;

-- Q21: joins=0, agg=True, sub=True, tables=3, rows=1, time=6.4ms
SELECT DISTINCT n.tag, n.version, COUNT(*) AS cnt
FROM num n
WHERE n.uom = 'pure' AND n.value IS NOT NULL
      AND EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version
                AND p.stmt = 'CF'
      )
GROUP BY n.tag, n.version
ORDER BY cnt DESC
LIMIT 100;

-- Q22: joins=2, agg=False, sub=False, tables=3, rows=200, time=6.4ms
SELECT s.name, p.stmt, t.tlabel, p.line, p.plabel
FROM pre p
JOIN sub s ON p.adsh = s.adsh
JOIN tag t ON p.tag = t.tag AND p.version = t.version
WHERE s.form = '10-Q' AND p.stmt = 'BS'
      AND t.custom = 0
ORDER BY s.name, p.line
LIMIT 200;

-- Q23: joins=1, agg=True, sub=True, tables=3, rows=50, time=6.4ms
SELECT s.name, n.tag, n.value
FROM num n
JOIN sub s ON n.adsh = s.adsh
WHERE n.uom = 'USD' AND s.fy = 2024 AND n.value IS NOT NULL
      AND n.value = (
          SELECT MAX(n2.value)
          FROM num n2
          WHERE n2.tag = n.tag AND n2.adsh = n.adsh AND n2.uom = 'USD'
      )
ORDER BY n.value DESC
LIMIT 50;

-- Q24: joins=0, agg=True, sub=True, tables=3, rows=1, time=6.4ms
SELECT DISTINCT n.tag, n.version, COUNT(*) AS cnt
FROM num n
WHERE n.uom = 'pure' AND n.value IS NOT NULL
      AND EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version
                AND p.stmt = 'IS'
      )
GROUP BY n.tag, n.version
ORDER BY cnt DESC
LIMIT 200;

-- Q25: joins=1, agg=True, sub=True, tables=3, rows=200, time=6.4ms
SELECT s.name, n.tag, n.value
FROM num n
JOIN sub s ON n.adsh = s.adsh
WHERE n.uom = 'shares' AND s.fy = 2022 AND n.value IS NOT NULL
      AND n.value = (
          SELECT MAX(n2.value)
          FROM num n2
          WHERE n2.tag = n.tag AND n2.adsh = n.adsh AND n2.uom = 'shares'
      )
ORDER BY n.value DESC
LIMIT 200;

-- Q26: joins=2, agg=True, sub=False, tables=4, rows=50, time=6.4ms
SELECT s.name, p.stmt, n.tag, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'USD' AND p.stmt = 'CI' AND s.fy = 2022
      AND n.value IS NOT NULL
GROUP BY s.name, p.stmt, n.tag, p.plabel
ORDER BY total_value DESC
LIMIT 50;

-- Q27: joins=2, agg=True, sub=False, tables=4, rows=200, time=6.4ms
SELECT s.name, p.stmt, n.tag, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'USD' AND p.stmt = 'IS' AND s.fy = 2023
      AND n.value IS NOT NULL
GROUP BY s.name, p.stmt, n.tag, p.plabel
ORDER BY total_value DESC
LIMIT 200;

-- Q28: joins=1, agg=True, sub=False, tables=2, rows=1, time=6.5ms
SELECT t.tlabel, t.datatype, COUNT(*) AS usage_count,
       COUNT(DISTINCT p.adsh) AS filing_count
FROM pre p
JOIN tag t ON p.tag = t.tag AND p.version = t.version
WHERE p.stmt = 'CF' AND t.tlabel IS NOT NULL
GROUP BY t.tlabel, t.datatype
HAVING COUNT(*) > 5
ORDER BY usage_count DESC
LIMIT 50;

-- Q29: joins=0, agg=True, sub=True, tables=3, rows=1, time=6.5ms
SELECT DISTINCT n.tag, n.version, COUNT(*) AS cnt
FROM num n
WHERE n.uom = 'pure' AND n.value IS NOT NULL
      AND EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version
                AND p.stmt = 'CF'
      )
GROUP BY n.tag, n.version
ORDER BY cnt DESC
LIMIT 50;

-- Q30: joins=0, agg=True, sub=True, tables=3, rows=1, time=6.6ms
SELECT DISTINCT n.tag, n.version, COUNT(*) AS cnt
FROM num n
WHERE n.uom = 'USD' AND n.value IS NOT NULL
      AND EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version
                AND p.stmt = 'EQ'
      )
GROUP BY n.tag, n.version
ORDER BY cnt DESC
LIMIT 50;

-- Q31: joins=0, agg=True, sub=True, tables=3, rows=1, time=6.6ms
SELECT DISTINCT n.tag, n.version, COUNT(*) AS cnt
FROM num n
WHERE n.uom = 'USD' AND n.value IS NOT NULL
      AND EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version
                AND p.stmt = 'BS'
      )
GROUP BY n.tag, n.version
ORDER BY cnt DESC
LIMIT 50;

-- Q32: joins=2, agg=True, sub=False, tables=4, rows=50, time=6.6ms
SELECT s.name, p.stmt, n.tag, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'shares' AND p.stmt = 'IS' AND s.fy = 2023
      AND n.value IS NOT NULL
GROUP BY s.name, p.stmt, n.tag, p.plabel
ORDER BY total_value DESC
LIMIT 50;

-- Q33: joins=1, agg=True, sub=False, tables=2, rows=5, time=6.6ms
SELECT n.tag, t.tlabel, t.datatype,
       COUNT(DISTINCT n.adsh) AS num_filings,
       COUNT(*) AS total_entries,
       SUM(CASE WHEN n.value > 0 THEN 1 ELSE 0 END) AS positive_count,
       SUM(CASE WHEN n.value < 0 THEN 1 ELSE 0 END) AS negative_count
FROM num n
JOIN tag t ON n.tag = t.tag AND n.version = t.version
WHERE n.ddate BETWEEN 20220101 AND 20241231 AND n.value IS NOT NULL
      AND t.custom = 0
GROUP BY n.tag, t.tlabel, t.datatype
HAVING COUNT(DISTINCT n.adsh) > 100
ORDER BY num_filings DESC
LIMIT 1000;

-- Q34: joins=2, agg=True, sub=False, tables=4, rows=200, time=6.7ms
SELECT s.name, p.stmt, n.tag, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'pure' AND p.stmt = 'EQ' AND s.fy = 2024
      AND n.value IS NOT NULL
GROUP BY s.name, p.stmt, n.tag, p.plabel
ORDER BY total_value DESC
LIMIT 200;

-- Q35: joins=1, agg=True, sub=True, tables=3, rows=100, time=6.8ms
SELECT s.name, n.tag, n.value
FROM num n
JOIN sub s ON n.adsh = s.adsh
WHERE n.uom = 'pure' AND s.fy = 2024 AND n.value IS NOT NULL
      AND n.value = (
          SELECT MAX(n2.value)
          FROM num n2
          WHERE n2.tag = n.tag AND n2.adsh = n.adsh AND n2.uom = 'pure'
      )
ORDER BY n.value DESC
LIMIT 100;

-- Q36: joins=0, agg=True, sub=True, tables=3, rows=1, time=6.8ms
SELECT DISTINCT n.tag, n.version, COUNT(*) AS cnt
FROM num n
WHERE n.uom = 'shares' AND n.value IS NOT NULL
      AND EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version
                AND p.stmt = 'BS'
      )
GROUP BY n.tag, n.version
ORDER BY cnt DESC
LIMIT 100;

-- Q37: joins=1, agg=True, sub=True, tables=3, rows=50, time=6.8ms
SELECT s.name, n.tag, n.value
FROM num n
JOIN sub s ON n.adsh = s.adsh
WHERE n.uom = 'shares' AND s.fy = 2024 AND n.value IS NOT NULL
      AND n.value = (
          SELECT MAX(n2.value)
          FROM num n2
          WHERE n2.tag = n.tag AND n2.adsh = n.adsh AND n2.uom = 'shares'
      )
ORDER BY n.value DESC
LIMIT 50;

-- Q38: joins=0, agg=True, sub=True, tables=3, rows=4, time=6.8ms
SELECT n.tag, n.version, COUNT(*) AS cnt, SUM(n.value) AS total
FROM num n
WHERE n.uom = 'shares' AND n.ddate BETWEEN 20220101 AND 20221231
      AND n.value IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version AND p.adsh = n.adsh
      )
GROUP BY n.tag, n.version
HAVING COUNT(*) > 10
ORDER BY cnt DESC
LIMIT 500;

-- Q39: joins=1, agg=True, sub=False, tables=3, rows=12, time=6.8ms
SELECT s.form, s.fy, COUNT(*) AS num_lines,
       COUNT(DISTINCT p.tag) AS distinct_tags,
       AVG(p.line) AS avg_line
FROM pre p
JOIN sub s ON p.adsh = s.adsh
WHERE p.stmt = 'CF'
GROUP BY s.form, s.fy
ORDER BY num_lines DESC
LIMIT 1000;

-- Q40: joins=1, agg=True, sub=True, tables=3, rows=100, time=6.9ms
SELECT s.name, n.tag, n.value
FROM num n
JOIN sub s ON n.adsh = s.adsh
WHERE n.uom = 'shares' AND s.fy = 2022 AND n.value IS NOT NULL
      AND n.value = (
          SELECT MAX(n2.value)
          FROM num n2
          WHERE n2.tag = n.tag AND n2.adsh = n.adsh AND n2.uom = 'shares'
      )
ORDER BY n.value DESC
LIMIT 100;

-- Q41: joins=1, agg=True, sub=False, tables=2, rows=1, time=6.9ms
SELECT t.tlabel, t.datatype, COUNT(*) AS usage_count,
       COUNT(DISTINCT p.adsh) AS filing_count
FROM pre p
JOIN tag t ON p.tag = t.tag AND p.version = t.version
WHERE p.stmt = 'EQ' AND t.tlabel IS NOT NULL
GROUP BY t.tlabel, t.datatype
HAVING COUNT(*) > 5
ORDER BY usage_count DESC
LIMIT 50;

-- Q42: joins=2, agg=True, sub=False, tables=4, rows=1000, time=7.0ms
SELECT s.name, p.stmt, n.tag, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'pure' AND p.stmt = 'CI' AND s.fy = 2024
      AND n.value IS NOT NULL
GROUP BY s.name, p.stmt, n.tag, p.plabel
ORDER BY total_value DESC
LIMIT 1000;

-- Q43: joins=0, agg=True, sub=True, tables=3, rows=1, time=7.0ms
SELECT DISTINCT n.tag, n.version, COUNT(*) AS cnt
FROM num n
WHERE n.uom = 'USD' AND n.value IS NOT NULL
      AND EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version
                AND p.stmt = 'CF'
      )
GROUP BY n.tag, n.version
ORDER BY cnt DESC
LIMIT 100;

-- Q44: joins=0, agg=True, sub=True, tables=3, rows=4, time=7.1ms
SELECT n.tag, n.version, COUNT(*) AS cnt, SUM(n.value) AS total
FROM num n
WHERE n.uom = 'pure' AND n.ddate BETWEEN 20220101 AND 20221231
      AND n.value IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version AND p.adsh = n.adsh
      )
GROUP BY n.tag, n.version
HAVING COUNT(*) > 10
ORDER BY cnt DESC
LIMIT 1000;

-- Q45: joins=0, agg=True, sub=True, tables=3, rows=1, time=7.2ms
SELECT DISTINCT n.tag, n.version, COUNT(*) AS cnt
FROM num n
WHERE n.uom = 'USD' AND n.value IS NOT NULL
      AND EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version
                AND p.stmt = 'IS'
      )
GROUP BY n.tag, n.version
ORDER BY cnt DESC
LIMIT 50;

-- Q46: joins=3, agg=True, sub=False, tables=4, rows=100, time=7.3ms
SELECT s.name, s.sic, t.tlabel, p.stmt, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN tag t ON n.tag = t.tag AND n.version = t.version
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'USD' AND s.form = '10-K' AND p.stmt = 'CI'
      AND n.value IS NOT NULL AND t.abstract = 0
GROUP BY s.name, s.sic, t.tlabel, p.stmt, p.plabel
HAVING COUNT(*) > 1
ORDER BY total_value DESC
LIMIT 100;

-- Q47: joins=2, agg=True, sub=False, tables=4, rows=200, time=7.4ms
SELECT s.name, p.stmt, n.tag, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'shares' AND p.stmt = 'BS' AND s.fy = 2022
      AND n.value IS NOT NULL
GROUP BY s.name, p.stmt, n.tag, p.plabel
ORDER BY total_value DESC
LIMIT 200;

-- Q48: joins=1, agg=True, sub=True, tables=3, rows=50, time=7.4ms
SELECT s.name, n.tag, n.value
FROM num n
JOIN sub s ON n.adsh = s.adsh
WHERE n.uom = 'shares' AND s.fy = 2023 AND n.value IS NOT NULL
      AND n.value = (
          SELECT MAX(n2.value)
          FROM num n2
          WHERE n2.tag = n.tag AND n2.adsh = n.adsh AND n2.uom = 'shares'
      )
ORDER BY n.value DESC
LIMIT 50;

-- Q49: joins=0, agg=True, sub=True, tables=3, rows=4, time=7.4ms
SELECT n.tag, n.version, COUNT(*) AS cnt, SUM(n.value) AS total
FROM num n
WHERE n.uom = 'pure' AND n.ddate BETWEEN 20230101 AND 20231231
      AND n.value IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version AND p.adsh = n.adsh
      )
GROUP BY n.tag, n.version
HAVING COUNT(*) > 10
ORDER BY cnt DESC
LIMIT 100;

-- Q50: joins=3, agg=True, sub=False, tables=4, rows=2, time=7.4ms
SELECT s.sic, t.tlabel, p.stmt,
       COUNT(DISTINCT s.cik) AS num_companies,
       SUM(n.value) AS total_value,
       AVG(n.value) AS avg_value
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN tag t ON n.tag = t.tag AND n.version = t.version
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'shares' AND p.stmt = 'EQ'
      AND s.sic BETWEEN 4000 AND 4999
      AND n.value IS NOT NULL AND t.abstract = 0
GROUP BY s.sic, t.tlabel, p.stmt
HAVING COUNT(DISTINCT s.cik) >= 2
ORDER BY total_value DESC
LIMIT 200;

-- Q51: joins=1, agg=True, sub=False, tables=3, rows=12, time=7.5ms
SELECT s.form, s.fy, COUNT(*) AS num_lines,
       COUNT(DISTINCT p.tag) AS distinct_tags,
       AVG(p.line) AS avg_line
FROM pre p
JOIN sub s ON p.adsh = s.adsh
WHERE p.stmt = 'CI'
GROUP BY s.form, s.fy
ORDER BY num_lines DESC
LIMIT 1000;

-- Q52: joins=0, agg=True, sub=True, tables=3, rows=4, time=7.5ms
SELECT n.tag, n.version, COUNT(*) AS cnt, SUM(n.value) AS total
FROM num n
WHERE n.uom = 'pure' AND n.ddate BETWEEN 20220101 AND 20241231
      AND n.value IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version AND p.adsh = n.adsh
      )
GROUP BY n.tag, n.version
HAVING COUNT(*) > 10
ORDER BY cnt DESC
LIMIT 1000;

-- Q53: joins=3, agg=True, sub=False, tables=4, rows=1, time=7.5ms
SELECT s.sic, t.tlabel, p.stmt,
       COUNT(DISTINCT s.cik) AS num_companies,
       SUM(n.value) AS total_value,
       AVG(n.value) AS avg_value
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN tag t ON n.tag = t.tag AND n.version = t.version
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'shares' AND p.stmt = 'IS'
      AND s.sic BETWEEN 2000 AND 3999
      AND n.value IS NOT NULL AND t.abstract = 0
GROUP BY s.sic, t.tlabel, p.stmt
HAVING COUNT(DISTINCT s.cik) >= 2
ORDER BY total_value DESC
LIMIT 500;

-- Q54: joins=0, agg=True, sub=True, tables=3, rows=4, time=7.5ms
SELECT n.tag, n.version, COUNT(*) AS cnt, SUM(n.value) AS total
FROM num n
WHERE n.uom = 'pure' AND n.ddate BETWEEN 20230101 AND 20231231
      AND n.value IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version AND p.adsh = n.adsh
      )
GROUP BY n.tag, n.version
HAVING COUNT(*) > 10
ORDER BY cnt DESC
LIMIT 1000;

-- Q55: joins=3, agg=True, sub=False, tables=4, rows=328, time=7.6ms
SELECT s.name, s.sic, t.tlabel, p.stmt, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN tag t ON n.tag = t.tag AND n.version = t.version
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'pure' AND s.form = '10-Q' AND p.stmt = 'EQ'
      AND n.value IS NOT NULL AND t.abstract = 0
GROUP BY s.name, s.sic, t.tlabel, p.stmt, p.plabel
HAVING COUNT(*) > 1
ORDER BY total_value DESC
LIMIT 1000;

-- Q56: joins=1, agg=True, sub=True, tables=3, rows=368, time=7.7ms
SELECT s.name, n.tag, n.value
FROM num n
JOIN sub s ON n.adsh = s.adsh
WHERE n.uom = 'shares' AND s.fy = 2023 AND n.value IS NOT NULL
      AND n.value = (
          SELECT MAX(n2.value)
          FROM num n2
          WHERE n2.tag = n.tag AND n2.adsh = n.adsh AND n2.uom = 'shares'
      )
ORDER BY n.value DESC
LIMIT 1000;

-- Q57: joins=3, agg=True, sub=False, tables=4, rows=50, time=7.8ms
SELECT s.name, s.sic, t.tlabel, p.stmt, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN tag t ON n.tag = t.tag AND n.version = t.version
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'USD' AND s.form = '10-Q' AND p.stmt = 'EQ'
      AND n.value IS NOT NULL AND t.abstract = 0
GROUP BY s.name, s.sic, t.tlabel, p.stmt, p.plabel
HAVING COUNT(*) > 1
ORDER BY total_value DESC
LIMIT 50;

-- Q58: joins=3, agg=True, sub=False, tables=4, rows=1, time=7.8ms
SELECT s.sic, t.tlabel, p.stmt,
       COUNT(DISTINCT s.cik) AS num_companies,
       SUM(n.value) AS total_value,
       AVG(n.value) AS avg_value
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN tag t ON n.tag = t.tag AND n.version = t.version
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'pure' AND p.stmt = 'BS'
      AND s.sic BETWEEN 6000 AND 6799
      AND n.value IS NOT NULL AND t.abstract = 0
GROUP BY s.sic, t.tlabel, p.stmt
HAVING COUNT(DISTINCT s.cik) >= 2
ORDER BY total_value DESC
LIMIT 50;

-- Q59: joins=0, agg=True, sub=True, tables=3, rows=4, time=7.8ms
SELECT n.tag, n.version, COUNT(*) AS cnt, SUM(n.value) AS total
FROM num n
WHERE n.uom = 'shares' AND n.ddate BETWEEN 20230101 AND 20231231
      AND n.value IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version AND p.adsh = n.adsh
      )
GROUP BY n.tag, n.version
HAVING COUNT(*) > 10
ORDER BY cnt DESC
LIMIT 100;

-- Q60: joins=0, agg=True, sub=True, tables=3, rows=4, time=7.9ms
SELECT n.tag, n.version, COUNT(*) AS cnt, SUM(n.value) AS total
FROM num n
WHERE n.uom = 'shares' AND n.ddate BETWEEN 20220101 AND 20221231
      AND n.value IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version AND p.adsh = n.adsh
      )
GROUP BY n.tag, n.version
HAVING COUNT(*) > 10
ORDER BY cnt DESC
LIMIT 100;

-- Q61: joins=3, agg=True, sub=False, tables=4, rows=1, time=8.0ms
SELECT s.sic, t.tlabel, p.stmt,
       COUNT(DISTINCT s.cik) AS num_companies,
       SUM(n.value) AS total_value,
       AVG(n.value) AS avg_value
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN tag t ON n.tag = t.tag AND n.version = t.version
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'pure' AND p.stmt = 'EQ'
      AND s.sic BETWEEN 6000 AND 6799
      AND n.value IS NOT NULL AND t.abstract = 0
GROUP BY s.sic, t.tlabel, p.stmt
HAVING COUNT(DISTINCT s.cik) >= 2
ORDER BY total_value DESC
LIMIT 500;

-- Q62: joins=0, agg=True, sub=True, tables=3, rows=4, time=8.0ms
SELECT n.tag, n.version, COUNT(*) AS cnt, SUM(n.value) AS total
FROM num n
WHERE n.uom = 'USD' AND n.ddate BETWEEN 20230101 AND 20231231
      AND n.value IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version AND p.adsh = n.adsh
      )
GROUP BY n.tag, n.version
HAVING COUNT(*) > 10
ORDER BY cnt DESC
LIMIT 1000;

-- Q63: joins=1, agg=True, sub=True, tables=3, rows=200, time=8.0ms
SELECT s.name, n.tag, n.value
FROM num n
JOIN sub s ON n.adsh = s.adsh
WHERE n.uom = 'USD' AND s.fy = 2024 AND n.value IS NOT NULL
      AND n.value = (
          SELECT MAX(n2.value)
          FROM num n2
          WHERE n2.tag = n.tag AND n2.adsh = n.adsh AND n2.uom = 'USD'
      )
ORDER BY n.value DESC
LIMIT 200;

-- Q64: joins=3, agg=True, sub=False, tables=4, rows=200, time=8.0ms
SELECT s.name, s.sic, t.tlabel, p.stmt, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN tag t ON n.tag = t.tag AND n.version = t.version
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'shares' AND s.form = '8-K' AND p.stmt = 'CF'
      AND n.value IS NOT NULL AND t.abstract = 0
GROUP BY s.name, s.sic, t.tlabel, p.stmt, p.plabel
HAVING COUNT(*) > 1
ORDER BY total_value DESC
LIMIT 200;

-- Q65: joins=1, agg=True, sub=True, tables=3, rows=692, time=8.0ms
SELECT s.name, n.tag, n.value
FROM num n
JOIN sub s ON n.adsh = s.adsh
WHERE n.uom = 'USD' AND s.fy = 2022 AND n.value IS NOT NULL
      AND n.value = (
          SELECT MAX(n2.value)
          FROM num n2
          WHERE n2.tag = n.tag AND n2.adsh = n.adsh AND n2.uom = 'USD'
      )
ORDER BY n.value DESC
LIMIT 1000;

-- Q66: joins=0, agg=True, sub=True, tables=3, rows=1, time=8.1ms
SELECT DISTINCT n.tag, n.version, COUNT(*) AS cnt
FROM num n
WHERE n.uom = 'pure' AND n.value IS NOT NULL
      AND EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version
                AND p.stmt = 'BS'
      )
GROUP BY n.tag, n.version
ORDER BY cnt DESC
LIMIT 500;

-- Q67: joins=3, agg=True, sub=False, tables=4, rows=1, time=8.1ms
SELECT s.sic, t.tlabel, p.stmt,
       COUNT(DISTINCT s.cik) AS num_companies,
       SUM(n.value) AS total_value,
       AVG(n.value) AS avg_value
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN tag t ON n.tag = t.tag AND n.version = t.version
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'USD' AND p.stmt = 'EQ'
      AND s.sic BETWEEN 6000 AND 6799
      AND n.value IS NOT NULL AND t.abstract = 0
GROUP BY s.sic, t.tlabel, p.stmt
HAVING COUNT(DISTINCT s.cik) >= 2
ORDER BY total_value DESC
LIMIT 50;

-- Q68: joins=1, agg=True, sub=True, tables=3, rows=385, time=8.1ms
SELECT s.name, n.tag, n.value
FROM num n
JOIN sub s ON n.adsh = s.adsh
WHERE n.uom = 'pure' AND s.fy = 2023 AND n.value IS NOT NULL
      AND n.value = (
          SELECT MAX(n2.value)
          FROM num n2
          WHERE n2.tag = n.tag AND n2.adsh = n.adsh AND n2.uom = 'pure'
      )
ORDER BY n.value DESC
LIMIT 1000;

-- Q69: joins=2, agg=True, sub=False, tables=4, rows=200, time=8.2ms
SELECT s.name, p.stmt, n.tag, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'pure' AND p.stmt = 'IS' AND s.fy = 2024
      AND n.value IS NOT NULL
GROUP BY s.name, p.stmt, n.tag, p.plabel
ORDER BY total_value DESC
LIMIT 200;

-- Q70: joins=0, agg=True, sub=True, tables=3, rows=4, time=8.3ms
SELECT n.tag, n.version, COUNT(*) AS cnt, SUM(n.value) AS total
FROM num n
WHERE n.uom = 'pure' AND n.ddate BETWEEN 20240101 AND 20241231
      AND n.value IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version AND p.adsh = n.adsh
      )
GROUP BY n.tag, n.version
HAVING COUNT(*) > 10
ORDER BY cnt DESC
LIMIT 1000;

-- Q71: joins=0, agg=True, sub=True, tables=3, rows=1, time=8.4ms
SELECT DISTINCT n.tag, n.version, COUNT(*) AS cnt
FROM num n
WHERE n.uom = 'USD' AND n.value IS NOT NULL
      AND EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version
                AND p.stmt = 'CF'
      )
GROUP BY n.tag, n.version
ORDER BY cnt DESC
LIMIT 500;

-- Q72: joins=1, agg=True, sub=False, tables=3, rows=12, time=8.7ms
SELECT s.form, s.fy, COUNT(*) AS num_lines,
       COUNT(DISTINCT p.tag) AS distinct_tags,
       AVG(p.line) AS avg_line
FROM pre p
JOIN sub s ON p.adsh = s.adsh
WHERE p.stmt = 'CI'
GROUP BY s.form, s.fy
ORDER BY num_lines DESC
LIMIT 500;

-- Q73: joins=3, agg=True, sub=False, tables=4, rows=491, time=9.1ms
SELECT s.name, s.sic, t.tlabel, p.stmt, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN tag t ON n.tag = t.tag AND n.version = t.version
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'pure' AND s.form = '8-K' AND p.stmt = 'CI'
      AND n.value IS NOT NULL AND t.abstract = 0
GROUP BY s.name, s.sic, t.tlabel, p.stmt, p.plabel
HAVING COUNT(*) > 1
ORDER BY total_value DESC
LIMIT 1000;

-- Q74: joins=0, agg=True, sub=True, tables=3, rows=4, time=9.4ms
SELECT n.tag, n.version, COUNT(*) AS cnt, SUM(n.value) AS total
FROM num n
WHERE n.uom = 'pure' AND n.ddate BETWEEN 20220101 AND 20241231
      AND n.value IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version AND p.adsh = n.adsh
      )
GROUP BY n.tag, n.version
HAVING COUNT(*) > 10
ORDER BY cnt DESC
LIMIT 100;

-- Q75: joins=2, agg=True, sub=False, tables=4, rows=100, time=9.6ms
SELECT s.name, p.stmt, n.tag, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'shares' AND p.stmt = 'CI' AND s.fy = 2022
      AND n.value IS NOT NULL
GROUP BY s.name, p.stmt, n.tag, p.plabel
ORDER BY total_value DESC
LIMIT 100;

-- Q76: joins=0, agg=True, sub=False, tables=1, rows=14, time=9.7ms
SELECT stmt, rfile, COUNT(*) AS cnt,
       COUNT(DISTINCT adsh) AS num_filings,
       AVG(line) AS avg_line_num
FROM pre
WHERE stmt IS NOT NULL
GROUP BY stmt, rfile
ORDER BY cnt DESC;

-- Q77: joins=0, agg=True, sub=True, tables=3, rows=4, time=11.5ms
SELECT n.tag, n.version, COUNT(*) AS cnt, SUM(n.value) AS total
FROM num n
WHERE n.uom = 'USD' AND n.ddate BETWEEN 20220101 AND 20221231
      AND n.value IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version AND p.adsh = n.adsh
      )
GROUP BY n.tag, n.version
HAVING COUNT(*) > 10
ORDER BY cnt DESC
LIMIT 1000;

-- Q78: joins=0, agg=True, sub=True, tables=3, rows=4, time=13.7ms
SELECT n.tag, n.version, COUNT(*) AS cnt, SUM(n.value) AS total
FROM num n
WHERE n.uom = 'pure' AND n.ddate BETWEEN 20220101 AND 20241231
      AND n.value IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version AND p.adsh = n.adsh
      )
GROUP BY n.tag, n.version
HAVING COUNT(*) > 10
ORDER BY cnt DESC
LIMIT 200;

-- Q79: joins=1, agg=True, sub=False, tables=3, rows=15, time=13.8ms
SELECT s.fy, s.fp, COUNT(DISTINCT s.cik) AS num_companies,
       SUM(n.value) AS total_value, AVG(n.value) AS avg_value
FROM num n
JOIN sub s ON n.adsh = s.adsh
WHERE n.tag = 'NetIncomeLoss' AND n.uom = 'pure'
      AND n.value IS NOT NULL AND s.fp IN ('Q1', 'Q2', 'Q3', 'Q4', 'FY')
GROUP BY s.fy, s.fp
ORDER BY s.fy, s.fp;

-- Q80: joins=0, agg=True, sub=True, tables=3, rows=4, time=14.4ms
SELECT n.tag, n.version, COUNT(*) AS cnt, SUM(n.value) AS total
FROM num n
WHERE n.uom = 'USD' AND n.ddate BETWEEN 20240101 AND 20241231
      AND n.value IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version AND p.adsh = n.adsh
      )
GROUP BY n.tag, n.version
HAVING COUNT(*) > 10
ORDER BY cnt DESC
LIMIT 1000;

