-- SEC EDGAR Benchmark Queries
-- Generated by generate_queries.py (template-based random generation)
-- 50 queries selected from 557 generated

-- Q1: joins=2, agg=True, sub=True, tables=2, rows=50, time=5.5ms
SELECT s.name, s.cik, SUM(n.value) AS total_value
FROM num n
JOIN sub s ON n.adsh = s.adsh
WHERE n.uom = 'USD' AND s.fy = 2022 AND n.value IS NOT NULL
GROUP BY s.name, s.cik
HAVING SUM(n.value) > (
    SELECT AVG(sub_total) FROM (
        SELECT SUM(n2.value) AS sub_total
        FROM num n2
        JOIN sub s2 ON n2.adsh = s2.adsh
        WHERE n2.uom = 'USD' AND s2.fy = 2022 AND n2.value IS NOT NULL
        GROUP BY s2.cik
    ) avg_sub
)
ORDER BY total_value DESC
LIMIT 50;

-- Q2: joins=2, agg=True, sub=False, tables=4, rows=100, time=7.7ms
SELECT s.name, p.stmt, n.tag, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'pure' AND p.stmt = 'CF' AND s.fy = 2024
      AND n.value IS NOT NULL
GROUP BY s.name, p.stmt, n.tag, p.plabel
ORDER BY total_value DESC
LIMIT 100;

-- Q3: joins=1, agg=True, sub=False, tables=2, rows=1, time=7.7ms
SELECT t.tlabel, t.datatype, COUNT(*) AS usage_count,
       COUNT(DISTINCT p.adsh) AS filing_count
FROM pre p
JOIN tag t ON p.tag = t.tag AND p.version = t.version
WHERE p.stmt = 'CF' AND t.tlabel IS NOT NULL
GROUP BY t.tlabel, t.datatype
HAVING COUNT(*) > 5
ORDER BY usage_count DESC
LIMIT 500;

-- Q4: joins=1, agg=True, sub=True, tables=3, rows=500, time=7.8ms
SELECT s.name, n.tag, n.value
FROM num n
JOIN sub s ON n.adsh = s.adsh
WHERE n.uom = 'USD' AND s.fy = 2024 AND n.value IS NOT NULL
      AND n.value = (
          SELECT MAX(n2.value)
          FROM num n2
          WHERE n2.tag = n.tag AND n2.adsh = n.adsh AND n2.uom = 'USD'
      )
ORDER BY n.value DESC
LIMIT 500;

-- Q5: joins=3, agg=True, sub=False, tables=4, rows=312, time=7.8ms
SELECT s.name, s.sic, t.tlabel, p.stmt, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN tag t ON n.tag = t.tag AND n.version = t.version
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'pure' AND s.form = '10-K' AND p.stmt = 'CF'
      AND n.value IS NOT NULL AND t.abstract = 0
GROUP BY s.name, s.sic, t.tlabel, p.stmt, p.plabel
HAVING COUNT(*) > 1
ORDER BY total_value DESC
LIMIT 500;

-- Q6: joins=0, agg=True, sub=True, tables=3, rows=4, time=7.8ms
SELECT n.tag, n.version, COUNT(*) AS cnt, SUM(n.value) AS total
FROM num n
WHERE n.uom = 'pure' AND n.ddate BETWEEN 20230101 AND 20231231
      AND n.value IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version AND p.adsh = n.adsh
      )
GROUP BY n.tag, n.version
HAVING COUNT(*) > 10
ORDER BY cnt DESC
LIMIT 100;

-- Q7: joins=3, agg=True, sub=False, tables=4, rows=286, time=7.8ms
SELECT s.name, s.sic, t.tlabel, p.stmt, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN tag t ON n.tag = t.tag AND n.version = t.version
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'pure' AND s.form = '10-K' AND p.stmt = 'EQ'
      AND n.value IS NOT NULL AND t.abstract = 0
GROUP BY s.name, s.sic, t.tlabel, p.stmt, p.plabel
HAVING COUNT(*) > 1
ORDER BY total_value DESC
LIMIT 500;

-- Q8: joins=0, agg=True, sub=True, tables=3, rows=4, time=7.8ms
SELECT n.tag, n.version, COUNT(*) AS cnt, SUM(n.value) AS total
FROM num n
WHERE n.uom = 'shares' AND n.ddate BETWEEN 20240101 AND 20241231
      AND n.value IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version AND p.adsh = n.adsh
      )
GROUP BY n.tag, n.version
HAVING COUNT(*) > 10
ORDER BY cnt DESC
LIMIT 200;

-- Q9: joins=2, agg=False, sub=False, tables=3, rows=1000, time=7.8ms
SELECT s.name, p.stmt, t.tlabel, p.line, p.plabel
FROM pre p
JOIN sub s ON p.adsh = s.adsh
JOIN tag t ON p.tag = t.tag AND p.version = t.version
WHERE s.form = '8-K' AND p.stmt = 'IS'
      AND t.custom = 0
ORDER BY s.name, p.line
LIMIT 1000;

-- Q10: joins=2, agg=True, sub=False, tables=4, rows=500, time=7.8ms
SELECT s.name, p.stmt, n.tag, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'shares' AND p.stmt = 'CI' AND s.fy = 2022
      AND n.value IS NOT NULL
GROUP BY s.name, p.stmt, n.tag, p.plabel
ORDER BY total_value DESC
LIMIT 500;

-- Q11: joins=0, agg=True, sub=True, tables=3, rows=1, time=7.9ms
SELECT DISTINCT n.tag, n.version, COUNT(*) AS cnt
FROM num n
WHERE n.uom = 'USD' AND n.value IS NOT NULL
      AND EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version
                AND p.stmt = 'BS'
      )
GROUP BY n.tag, n.version
ORDER BY cnt DESC
LIMIT 100;

-- Q12: joins=2, agg=True, sub=False, tables=4, rows=1000, time=8.1ms
SELECT s.name, p.stmt, n.tag, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'USD' AND p.stmt = 'IS' AND s.fy = 2022
      AND n.value IS NOT NULL
GROUP BY s.name, p.stmt, n.tag, p.plabel
ORDER BY total_value DESC
LIMIT 1000;

-- Q13: joins=0, agg=True, sub=True, tables=3, rows=4, time=8.2ms
SELECT n.tag, n.version, COUNT(*) AS cnt, SUM(n.value) AS total
FROM num n
WHERE n.uom = 'shares' AND n.ddate BETWEEN 20230101 AND 20231231
      AND n.value IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version AND p.adsh = n.adsh
      )
GROUP BY n.tag, n.version
HAVING COUNT(*) > 10
ORDER BY cnt DESC
LIMIT 500;

-- Q14: joins=3, agg=True, sub=False, tables=4, rows=1, time=8.3ms
SELECT s.sic, t.tlabel, p.stmt,
       COUNT(DISTINCT s.cik) AS num_companies,
       SUM(n.value) AS total_value,
       AVG(n.value) AS avg_value
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN tag t ON n.tag = t.tag AND n.version = t.version
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'USD' AND p.stmt = 'CI'
      AND s.sic BETWEEN 7000 AND 8999
      AND n.value IS NOT NULL AND t.abstract = 0
GROUP BY s.sic, t.tlabel, p.stmt
HAVING COUNT(DISTINCT s.cik) >= 2
ORDER BY total_value DESC
LIMIT 200;

-- Q15: joins=0, agg=True, sub=True, tables=3, rows=4, time=8.3ms
SELECT n.tag, n.version, COUNT(*) AS cnt, SUM(n.value) AS total
FROM num n
WHERE n.uom = 'USD' AND n.ddate BETWEEN 20240101 AND 20241231
      AND n.value IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version AND p.adsh = n.adsh
      )
GROUP BY n.tag, n.version
HAVING COUNT(*) > 10
ORDER BY cnt DESC
LIMIT 500;

-- Q16: joins=0, agg=True, sub=True, tables=3, rows=4, time=8.3ms
SELECT n.tag, n.version, COUNT(*) AS cnt, SUM(n.value) AS total
FROM num n
WHERE n.uom = 'shares' AND n.ddate BETWEEN 20220101 AND 20241231
      AND n.value IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version AND p.adsh = n.adsh
      )
GROUP BY n.tag, n.version
HAVING COUNT(*) > 10
ORDER BY cnt DESC
LIMIT 200;

-- Q17: joins=0, agg=True, sub=True, tables=3, rows=1, time=8.3ms
SELECT DISTINCT n.tag, n.version, COUNT(*) AS cnt
FROM num n
WHERE n.uom = 'shares' AND n.value IS NOT NULL
      AND EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version
                AND p.stmt = 'CI'
      )
GROUP BY n.tag, n.version
ORDER BY cnt DESC
LIMIT 50;

-- Q18: joins=0, agg=True, sub=True, tables=3, rows=4, time=8.4ms
SELECT n.tag, n.version, COUNT(*) AS cnt, SUM(n.value) AS total
FROM num n
WHERE n.uom = 'pure' AND n.ddate BETWEEN 20230101 AND 20231231
      AND n.value IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version AND p.adsh = n.adsh
      )
GROUP BY n.tag, n.version
HAVING COUNT(*) > 10
ORDER BY cnt DESC
LIMIT 1000;

-- Q19: joins=2, agg=True, sub=False, tables=4, rows=200, time=8.4ms
SELECT s.name, p.stmt, n.tag, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'USD' AND p.stmt = 'BS' AND s.fy = 2022
      AND n.value IS NOT NULL
GROUP BY s.name, p.stmt, n.tag, p.plabel
ORDER BY total_value DESC
LIMIT 200;

-- Q20: joins=0, agg=True, sub=True, tables=3, rows=4, time=8.5ms
SELECT n.tag, n.version, COUNT(*) AS cnt, SUM(n.value) AS total
FROM num n
WHERE n.uom = 'shares' AND n.ddate BETWEEN 20240101 AND 20241231
      AND n.value IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version AND p.adsh = n.adsh
      )
GROUP BY n.tag, n.version
HAVING COUNT(*) > 10
ORDER BY cnt DESC
LIMIT 100;

-- Q21: joins=3, agg=True, sub=False, tables=4, rows=1, time=8.6ms
SELECT s.sic, t.tlabel, p.stmt,
       COUNT(DISTINCT s.cik) AS num_companies,
       SUM(n.value) AS total_value,
       AVG(n.value) AS avg_value
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN tag t ON n.tag = t.tag AND n.version = t.version
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'USD' AND p.stmt = 'IS'
      AND s.sic BETWEEN 7000 AND 8999
      AND n.value IS NOT NULL AND t.abstract = 0
GROUP BY s.sic, t.tlabel, p.stmt
HAVING COUNT(DISTINCT s.cik) >= 2
ORDER BY total_value DESC
LIMIT 1000;

-- Q22: joins=0, agg=True, sub=True, tables=3, rows=4, time=8.7ms
SELECT n.tag, n.version, COUNT(*) AS cnt, SUM(n.value) AS total
FROM num n
WHERE n.uom = 'USD' AND n.ddate BETWEEN 20240101 AND 20241231
      AND n.value IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version AND p.adsh = n.adsh
      )
GROUP BY n.tag, n.version
HAVING COUNT(*) > 10
ORDER BY cnt DESC
LIMIT 200;

-- Q23: joins=0, agg=True, sub=True, tables=3, rows=1, time=8.7ms
SELECT DISTINCT n.tag, n.version, COUNT(*) AS cnt
FROM num n
WHERE n.uom = 'USD' AND n.value IS NOT NULL
      AND EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version
                AND p.stmt = 'IS'
      )
GROUP BY n.tag, n.version
ORDER BY cnt DESC
LIMIT 200;

-- Q24: joins=0, agg=True, sub=True, tables=3, rows=4, time=8.7ms
SELECT n.tag, n.version, COUNT(*) AS cnt, SUM(n.value) AS total
FROM num n
WHERE n.uom = 'USD' AND n.ddate BETWEEN 20220101 AND 20221231
      AND n.value IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version AND p.adsh = n.adsh
      )
GROUP BY n.tag, n.version
HAVING COUNT(*) > 10
ORDER BY cnt DESC
LIMIT 500;

-- Q25: joins=3, agg=True, sub=False, tables=4, rows=436, time=8.7ms
SELECT s.name, s.sic, t.tlabel, p.stmt, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN tag t ON n.tag = t.tag AND n.version = t.version
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'shares' AND s.form = '10-Q' AND p.stmt = 'CI'
      AND n.value IS NOT NULL AND t.abstract = 0
GROUP BY s.name, s.sic, t.tlabel, p.stmt, p.plabel
HAVING COUNT(*) > 1
ORDER BY total_value DESC
LIMIT 1000;

-- Q26: joins=3, agg=True, sub=False, tables=4, rows=100, time=8.7ms
SELECT s.name, s.sic, t.tlabel, p.stmt, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN tag t ON n.tag = t.tag AND n.version = t.version
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'USD' AND s.form = '10-Q' AND p.stmt = 'IS'
      AND n.value IS NOT NULL AND t.abstract = 0
GROUP BY s.name, s.sic, t.tlabel, p.stmt, p.plabel
HAVING COUNT(*) > 1
ORDER BY total_value DESC
LIMIT 100;

-- Q27: joins=2, agg=True, sub=False, tables=4, rows=100, time=8.8ms
SELECT s.name, p.stmt, n.tag, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'pure' AND p.stmt = 'BS' AND s.fy = 2023
      AND n.value IS NOT NULL
GROUP BY s.name, p.stmt, n.tag, p.plabel
ORDER BY total_value DESC
LIMIT 100;

-- Q28: joins=3, agg=True, sub=False, tables=4, rows=500, time=8.8ms
SELECT s.name, s.sic, t.tlabel, p.stmt, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN tag t ON n.tag = t.tag AND n.version = t.version
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'pure' AND s.form = '8-K' AND p.stmt = 'IS'
      AND n.value IS NOT NULL AND t.abstract = 0
GROUP BY s.name, s.sic, t.tlabel, p.stmt, p.plabel
HAVING COUNT(*) > 1
ORDER BY total_value DESC
LIMIT 500;

-- Q29: joins=0, agg=True, sub=True, tables=3, rows=4, time=8.8ms
SELECT n.tag, n.version, COUNT(*) AS cnt, SUM(n.value) AS total
FROM num n
WHERE n.uom = 'pure' AND n.ddate BETWEEN 20220101 AND 20241231
      AND n.value IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version AND p.adsh = n.adsh
      )
GROUP BY n.tag, n.version
HAVING COUNT(*) > 10
ORDER BY cnt DESC
LIMIT 200;

-- Q30: joins=2, agg=True, sub=False, tables=4, rows=200, time=8.8ms
SELECT s.name, p.stmt, n.tag, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'shares' AND p.stmt = 'BS' AND s.fy = 2024
      AND n.value IS NOT NULL
GROUP BY s.name, p.stmt, n.tag, p.plabel
ORDER BY total_value DESC
LIMIT 200;

-- Q31: joins=3, agg=True, sub=False, tables=4, rows=100, time=8.9ms
SELECT s.name, s.sic, t.tlabel, p.stmt, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN tag t ON n.tag = t.tag AND n.version = t.version
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'USD' AND s.form = '10-K' AND p.stmt = 'BS'
      AND n.value IS NOT NULL AND t.abstract = 0
GROUP BY s.name, s.sic, t.tlabel, p.stmt, p.plabel
HAVING COUNT(*) > 1
ORDER BY total_value DESC
LIMIT 100;

-- Q32: joins=2, agg=True, sub=False, tables=4, rows=500, time=9.0ms
SELECT s.name, p.stmt, n.tag, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'pure' AND p.stmt = 'CI' AND s.fy = 2023
      AND n.value IS NOT NULL
GROUP BY s.name, p.stmt, n.tag, p.plabel
ORDER BY total_value DESC
LIMIT 500;

-- Q33: joins=3, agg=True, sub=False, tables=4, rows=1, time=9.3ms
SELECT s.sic, t.tlabel, p.stmt,
       COUNT(DISTINCT s.cik) AS num_companies,
       SUM(n.value) AS total_value,
       AVG(n.value) AS avg_value
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN tag t ON n.tag = t.tag AND n.version = t.version
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'shares' AND p.stmt = 'IS'
      AND s.sic BETWEEN 6000 AND 6799
      AND n.value IS NOT NULL AND t.abstract = 0
GROUP BY s.sic, t.tlabel, p.stmt
HAVING COUNT(DISTINCT s.cik) >= 2
ORDER BY total_value DESC
LIMIT 200;

-- Q34: joins=3, agg=True, sub=False, tables=4, rows=1, time=9.4ms
SELECT s.sic, t.tlabel, p.stmt,
       COUNT(DISTINCT s.cik) AS num_companies,
       SUM(n.value) AS total_value,
       AVG(n.value) AS avg_value
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN tag t ON n.tag = t.tag AND n.version = t.version
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'USD' AND p.stmt = 'CI'
      AND s.sic BETWEEN 2000 AND 3999
      AND n.value IS NOT NULL AND t.abstract = 0
GROUP BY s.sic, t.tlabel, p.stmt
HAVING COUNT(DISTINCT s.cik) >= 2
ORDER BY total_value DESC
LIMIT 1000;

-- Q35: joins=3, agg=True, sub=False, tables=4, rows=1000, time=9.5ms
SELECT s.name, s.sic, t.tlabel, p.stmt, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN tag t ON n.tag = t.tag AND n.version = t.version
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'USD' AND s.form = '10-Q' AND p.stmt = 'IS'
      AND n.value IS NOT NULL AND t.abstract = 0
GROUP BY s.name, s.sic, t.tlabel, p.stmt, p.plabel
HAVING COUNT(*) > 1
ORDER BY total_value DESC
LIMIT 1000;

-- Q36: joins=3, agg=True, sub=False, tables=4, rows=50, time=9.5ms
SELECT s.name, s.sic, t.tlabel, p.stmt, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN tag t ON n.tag = t.tag AND n.version = t.version
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'shares' AND s.form = '10-Q' AND p.stmt = 'IS'
      AND n.value IS NOT NULL AND t.abstract = 0
GROUP BY s.name, s.sic, t.tlabel, p.stmt, p.plabel
HAVING COUNT(*) > 1
ORDER BY total_value DESC
LIMIT 50;

-- Q37: joins=0, agg=True, sub=True, tables=3, rows=4, time=9.6ms
SELECT n.tag, n.version, COUNT(*) AS cnt, SUM(n.value) AS total
FROM num n
WHERE n.uom = 'USD' AND n.ddate BETWEEN 20230101 AND 20231231
      AND n.value IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version AND p.adsh = n.adsh
      )
GROUP BY n.tag, n.version
HAVING COUNT(*) > 10
ORDER BY cnt DESC
LIMIT 100;

-- Q38: joins=3, agg=True, sub=False, tables=4, rows=1, time=9.6ms
SELECT s.sic, t.tlabel, p.stmt,
       COUNT(DISTINCT s.cik) AS num_companies,
       SUM(n.value) AS total_value,
       AVG(n.value) AS avg_value
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN tag t ON n.tag = t.tag AND n.version = t.version
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'shares' AND p.stmt = 'EQ'
      AND s.sic BETWEEN 6000 AND 6799
      AND n.value IS NOT NULL AND t.abstract = 0
GROUP BY s.sic, t.tlabel, p.stmt
HAVING COUNT(DISTINCT s.cik) >= 2
ORDER BY total_value DESC
LIMIT 500;

-- Q39: joins=2, agg=True, sub=False, tables=4, rows=50, time=9.7ms
SELECT s.name, p.stmt, n.tag, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'USD' AND p.stmt = 'IS' AND s.fy = 2024
      AND n.value IS NOT NULL
GROUP BY s.name, p.stmt, n.tag, p.plabel
ORDER BY total_value DESC
LIMIT 50;

-- Q40: joins=3, agg=True, sub=False, tables=4, rows=395, time=10.0ms
SELECT s.name, s.sic, t.tlabel, p.stmt, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN tag t ON n.tag = t.tag AND n.version = t.version
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'shares' AND s.form = '10-K' AND p.stmt = 'BS'
      AND n.value IS NOT NULL AND t.abstract = 0
GROUP BY s.name, s.sic, t.tlabel, p.stmt, p.plabel
HAVING COUNT(*) > 1
ORDER BY total_value DESC
LIMIT 1000;

-- Q41: joins=1, agg=True, sub=True, tables=3, rows=100, time=10.1ms
SELECT s.name, n.tag, n.value
FROM num n
JOIN sub s ON n.adsh = s.adsh
WHERE n.uom = 'USD' AND s.fy = 2024 AND n.value IS NOT NULL
      AND n.value = (
          SELECT MAX(n2.value)
          FROM num n2
          WHERE n2.tag = n.tag AND n2.adsh = n.adsh AND n2.uom = 'USD'
      )
ORDER BY n.value DESC
LIMIT 100;

-- Q42: joins=3, agg=True, sub=False, tables=4, rows=1000, time=10.2ms
SELECT s.name, s.sic, t.tlabel, p.stmt, p.plabel,
       SUM(n.value) AS total_value, COUNT(*) AS cnt
FROM num n
JOIN sub s ON n.adsh = s.adsh
JOIN tag t ON n.tag = t.tag AND n.version = t.version
JOIN pre p ON n.adsh = p.adsh AND n.tag = p.tag AND n.version = p.version
WHERE n.uom = 'USD' AND s.form = '8-K' AND p.stmt = 'EQ'
      AND n.value IS NOT NULL AND t.abstract = 0
GROUP BY s.name, s.sic, t.tlabel, p.stmt, p.plabel
HAVING COUNT(*) > 1
ORDER BY total_value DESC
LIMIT 1000;

-- Q43: joins=0, agg=True, sub=True, tables=3, rows=4, time=10.2ms
SELECT n.tag, n.version, COUNT(*) AS cnt, SUM(n.value) AS total
FROM num n
WHERE n.uom = 'shares' AND n.ddate BETWEEN 20230101 AND 20231231
      AND n.value IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version AND p.adsh = n.adsh
      )
GROUP BY n.tag, n.version
HAVING COUNT(*) > 10
ORDER BY cnt DESC
LIMIT 50;

-- Q44: joins=0, agg=True, sub=True, tables=3, rows=4, time=10.3ms
SELECT n.tag, n.version, COUNT(*) AS cnt, SUM(n.value) AS total
FROM num n
WHERE n.uom = 'USD' AND n.ddate BETWEEN 20220101 AND 20241231
      AND n.value IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version AND p.adsh = n.adsh
      )
GROUP BY n.tag, n.version
HAVING COUNT(*) > 10
ORDER BY cnt DESC
LIMIT 500;

-- Q45: joins=0, agg=True, sub=True, tables=3, rows=4, time=10.7ms
SELECT n.tag, n.version, COUNT(*) AS cnt, SUM(n.value) AS total
FROM num n
WHERE n.uom = 'USD' AND n.ddate BETWEEN 20220101 AND 20221231
      AND n.value IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version AND p.adsh = n.adsh
      )
GROUP BY n.tag, n.version
HAVING COUNT(*) > 10
ORDER BY cnt DESC
LIMIT 50;

-- Q46: joins=1, agg=True, sub=False, tables=2, rows=1, time=11.3ms
SELECT t.tlabel, t.datatype, COUNT(*) AS usage_count,
       COUNT(DISTINCT p.adsh) AS filing_count
FROM pre p
JOIN tag t ON p.tag = t.tag AND p.version = t.version
WHERE p.stmt = 'CF' AND t.tlabel IS NOT NULL
GROUP BY t.tlabel, t.datatype
HAVING COUNT(*) > 5
ORDER BY usage_count DESC
LIMIT 1000;

-- Q47: joins=0, agg=True, sub=True, tables=3, rows=4, time=11.6ms
SELECT n.tag, n.version, COUNT(*) AS cnt, SUM(n.value) AS total
FROM num n
WHERE n.uom = 'USD' AND n.ddate BETWEEN 20220101 AND 20241231
      AND n.value IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM pre p
          WHERE p.tag = n.tag AND p.version = n.version AND p.adsh = n.adsh
      )
GROUP BY n.tag, n.version
HAVING COUNT(*) > 10
ORDER BY cnt DESC
LIMIT 50;

-- Q48: joins=0, agg=True, sub=False, tables=1, rows=14, time=12.2ms
SELECT stmt, rfile, COUNT(*) AS cnt,
       COUNT(DISTINCT adsh) AS num_filings,
       AVG(line) AS avg_line_num
FROM pre
WHERE stmt IS NOT NULL
GROUP BY stmt, rfile
ORDER BY cnt DESC;

-- Q49: joins=1, agg=True, sub=True, tables=3, rows=100, time=14.2ms
SELECT s.name, n.tag, n.value
FROM num n
JOIN sub s ON n.adsh = s.adsh
WHERE n.uom = 'pure' AND s.fy = 2023 AND n.value IS NOT NULL
      AND n.value = (
          SELECT MAX(n2.value)
          FROM num n2
          WHERE n2.tag = n.tag AND n2.adsh = n.adsh AND n2.uom = 'pure'
      )
ORDER BY n.value DESC
LIMIT 100;

-- Q50: joins=1, agg=True, sub=False, tables=3, rows=12, time=18.2ms
SELECT s.form, s.fy, COUNT(*) AS num_lines,
       COUNT(DISTINCT p.tag) AS distinct_tags,
       AVG(p.line) AS avg_line
FROM pre p
JOIN sub s ON p.adsh = s.adsh
WHERE p.stmt = 'CI'
GROUP BY s.form, s.fy
ORDER BY num_lines DESC
LIMIT 200;

